import { notFound } from "next/navigation";

const OLD = "https://peptide-science-animations-store-nqfz77bs7.vercel.app";

type Product = {name:string;category:string;price:number;concentration:string;description:string;image?:string;about?:string;overview?:string;benefits?:string[];coa?:string;coaImage?:string;coaDate?:string;variants?:{label:string;price:number;slug:string}[]};

const base: Record<string,Product> = {
  "retatrutide-5mg": {name:"Retatrutide 5mg",category:"Metabolic",price:89.99,concentration:"5mg/vial",description:"Triple receptor agonist (GLP-1, GIP, Glucagon) — 5mg entry-level vial for dose-titration research.",image:"/products/retatrutide-10mg.png",about:"Retatrutide is a novel triple-receptor agonist targeting GLP-1, GIP, and glucagon receptors simultaneously. This 5mg vial is designed for titration-phase research protocols requiring smaller starting doses.",overview:"The 5mg vial format supports early-phase dose escalation research where incremental receptor engagement is studied across the three target pathways. For in-vitro and laboratory research use only.",benefits:["Triple-receptor dose titration","Glucagon pathway initiation","Metabolic homeostasis research","Entry-level research format"],coa:"https://www.janoshik.com/verify/RS3NDY1U7V26E",coaImage:"/coa/retatrutide.png",coaDate:"07 Jan 2026",variants:[{label:"5mg",price:89.99,slug:"retatrutide-5mg"},{label:"10mg",price:149.99,slug:"retatrutide-10mg"},{label:"15mg",price:199.99,slug:"retatrutide-15mg"}]},
  "retatrutide-10mg": {name:"Retatrutide",category:"Metabolic",price:149.99,concentration:"10mg/vial",description:"Triple receptor agonist (GLP-1, GIP, Glucagon) under active investigation for metabolic regulation.",image:"/products/retatrutide-10mg.png",about:"Retatrutide is a novel triple-receptor agonist targeting the GLP-1, GIP, and glucagon receptors simultaneously. It is currently the subject of Phase 3 clinical research exploring its potential in metabolic homeostasis and body-composition modulation.",overview:"In preclinical and early clinical research, retatrutide has demonstrated potent activity across all three receptor pathways. The glucagon component adds an element of hepatic glucose output regulation not seen in dual GLP-1/GIP compounds, making it a highly differentiated investigational molecule. All use is strictly for in-vitro and laboratory research contexts.",benefits:["Triple-receptor activity","Metabolic homeostasis research","Glucose modulation","Adipose tissue studies"],coa:"https://www.janoshik.com/verify/RS3NDY1U7V26E",coaImage:"/coa/retatrutide.png",coaDate:"07 Jan 2026",variants:[{label:"5mg",price:89.99,slug:"retatrutide-5mg"},{label:"10mg",price:149.99,slug:"retatrutide-10mg"},{label:"15mg",price:199.99,slug:"retatrutide-15mg"}]},
  "retatrutide-15mg": {name:"Retatrutide 15mg",category:"Metabolic",price:199.99,concentration:"15mg/vial",description:"Triple receptor agonist (GLP-1, GIP, Glucagon) — high-dose 15mg vial for advanced metabolic research.",image:"/products/retatrutide-10mg.png",about:"Retatrutide 15mg provides a high-concentration vial for advanced research protocols requiring extended or higher-dose triple-receptor agonism across the GLP-1, GIP, and glucagon pathways.",overview:"This 15mg format is suited for extended research timelines and high-dose experimental designs exploring receptor engagement across all three incretin/glucagon axes. For in-vitro and laboratory research use only.",benefits:["High-dose triple-receptor research","Extended protocol support","Advanced adipose tissue studies","Hepatic glucose dynamics research"],coa:"https://www.janoshik.com/verify/RS3NDY1U7V26E",coaImage:"/coa/retatrutide.png",coaDate:"07 Jan 2026",variants:[{label:"5mg",price:89.99,slug:"retatrutide-5mg"},{label:"10mg",price:149.99,slug:"retatrutide-10mg"},{label:"15mg",price:199.99,slug:"retatrutide-15mg"}]},
  "tirzepatide-10mg": {name:"Tirzepatide",category:"Metabolic",price:139.99,concentration:"10mg/vial",description:"Dual GLP-1 / GIP receptor agonist for glycemic and metabolic research.",image:"/products/tirzepatide-10mg.png",about:"Tirzepatide is a dual GIP and GLP-1 receptor agonist studied for its interaction with incretin signaling pathways involved in metabolic research.",overview:"Researchers study tirzepatide across dual incretin pathways to better understand metabolic signaling, glucose-related mechanisms, and energy-balance pathways under controlled laboratory conditions.",benefits:["Dual incretin receptor activity","GIP receptor signaling","GLP-1 receptor signaling","Metabolic pathway research"]},
  "aod-9604": {name:"AOD-9604",category:"Metabolic",price:99.99,concentration:"5mg/vial",description:"C-terminal HGH fragment investigated for lipolytic activity without affecting blood glucose or IGF-1."},
  "igf-1-lr3": {name:"IGF-1 LR3",category:"Growth Hormone",price:189.99,concentration:"1mg/vial",description:"Long-R3 analogue of IGF-1 with extended half-life for downstream GH axis research.",image:"/products/igf-1-lr3.png"},
  "cjc-1295-ipamorelin": {name:"CJC-1295 / Ipamorelin Blend",category:"Growth Hormone",price:109.99,concentration:"10mg/vial (5mg+5mg)",description:"Synergistic GHRH + GHRP blend for pulsatile GH axis research.",image:"/products/cjc-ipa-blend.png"},
  "tesamorelin-5mg": {name:"Tesamorelin",category:"Growth Hormone",price:89.99,concentration:"5mg/vial",description:"Stabilized GHRH analogue studied for GH axis modulation and visceral adipose tissue research.",image:"/products/tesamorelin-5mg.png"},
  "bpc-157-tablets": {name:"BPC-157 Tablets",category:"Regenerative",price:249.99,concentration:"500mcg/tablet — 100 tablets",description:"Oral BPC-157 tablets studied for GI mucosal repair and systemic tissue-regeneration research."},
  "bpc-157-tb500": {name:"BPC-157 / TB-500 Blend",category:"Regenerative",price:109.99,concentration:"10mg/vial (5mg+5mg)",description:"Dual-action regenerative blend combining BPC-157 and TB-500 for synergistic tissue repair research.",image:"/products/bpc-157-tb500-blend.png"},
  "ghk-cu-100mg": {name:"GHK-Cu",category:"Regenerative",price:89.99,concentration:"100mg/vial",description:"Copper-binding tripeptide with broad research in wound healing, collagen, and gene expression modulation.",image:"/products/ghk-cu-100mg.png"},
  "klow80-80mg": {name:"Klow Blend 80mg",category:"Regenerative",price:229.99,concentration:"80mg/vial",description:"Advanced four-compound regenerative blend adding KPV to the Glow Blend base.",image:"/products/klow80-80mg.png"},
  "semax-5mg": {name:"Semax",category:"Nootropic",price:89.99,concentration:"5mg/vial",description:"Synthetic ACTH(4-10) analogue studied for neuroprotective and cognitive research via BDNF modulation.",image:"/products/semax-5mg.png"},
  "selank-10mg": {name:"Selank",category:"Nootropic",price:89.99,concentration:"10mg/vial",description:"Synthetic tuftsin analogue studied for nootropic and immunomodulatory effects.",image:"/products/selank-5mg.png"},
  "ss31-10mg": {name:"SS-31",category:"Longevity",price:129.99,concentration:"10mg/vial",description:"Mitochondria-targeted tetrapeptide studied for oxidative stress and mitochondrial membrane integrity.",image:"/products/ss31-10mg.png"},
  "nad-plus": {name:"NAD+",category:"Longevity",price:179.99,concentration:"1000mg/vial",description:"Nicotinamide adenine dinucleotide — essential cofactor studied for sirtuin activation, DNA repair, and mitochondrial function.",image:"/products/nad-plus-500mg.png"},
  "mots-c-10mg": {name:"MOTS-c",category:"Longevity",price:99.99,concentration:"10mg/vial",description:"Mitochondrial-derived peptide that regulates metabolic homeostasis and insulin sensitivity.",image:"/products/mots-c-10mg.png"},
  "kpv-10mg": {name:"KPV",category:"Regenerative",price:84.99,concentration:"10mg/vial",description:"C-terminal alpha-MSH tripeptide studied for anti-inflammatory and mucosal-repair pathways.",image:"/products/kpv-10mg.png"},
  "pt141-10mg": {name:"PT-141",category:"Specialized",price:99.99,concentration:"10mg/vial",description:"Melanocortin receptor agonist studied for CNS-mediated signaling research.",image:"/products/pt141-10mg.png"},
  "kisspeptin-5mg": {name:"Kisspeptin",category:"Specialized",price:99.99,concentration:"5mg/vial",description:"Hypothalamic neuropeptide studied in GnRH and HPG-axis research.",image:"/products/kisspeptin-5mg.png"},
  "thymosin-alpha-1": {name:"Thymosin Alpha-1",category:"Specialized",price:149.99,concentration:"10mg/vial",description:"Thymic peptide studied in T-cell activation and immune-signaling research.",image:"/products/thymosin-alpha-1.png"},
  "epithalon-10mg": {name:"Epithalon",category:"Longevity",price:89.99,concentration:"10mg/vial",description:"Tetrapeptide studied in telomerase and longevity-biology research.",image:"/products/epithalon-10mg.png"},
  "glutathione-1500mg": {name:"Glutathione",category:"Longevity",price:114.99,concentration:"1500mg/vial",description:"Antioxidant tripeptide studied in oxidative-stress and detoxification research.",image:"/products/glutathione-1500mg.png"},
  "bacteriostatic-water": {name:"Bacteriostatic Water",category:"Specialized",price:29.99,concentration:"1.5ml/vial",description:"0.9% benzyl alcohol sterile water for laboratory reconstitution workflows."}
};

function hydrate(p: Product): Product {
  return {...p, about:p.about || `${p.name} is a research compound studied within ${p.category.toLowerCase()} research models and controlled laboratory settings.`, overview:p.overview || `${p.name} is investigated for its relevant molecular signaling pathways and research applications. All use is strictly for in-vitro and laboratory research contexts.`, benefits:p.benefits || ["Molecular pathway research","Controlled laboratory studies","Mechanistic research","Analytical applications"]};
}

export async function generateMetadata({params}:{params:Promise<{slug:string}>}) { const {slug}=await params; const p=base[slug]; return p ? {title:`${p.name} ${p.concentration} — Lion Elite Wellness`,description:p.description} : {}; }

export default async function ProductPage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const raw=base[slug]; if(!raw) notFound(); const p=hydrate(raw);
  return <main className="detail-page">
    <div className="detail-top"><a href="/">← Back to Shop</a><span>Lion Elite Wellness — Research Grade</span></div>
    <div className="detail-shell">
      <section><span className="detail-category">{p.category}</span><h1>{p.name}</h1><div className="detail-conc">{p.concentration}</div><p className="detail-summary">{p.description}</p>
        <div className="detail-image">{p.image?<img src={`${OLD}${p.image}`} alt={`${p.name} vial`}/>:<div className="detail-placeholder">LE</div>}</div>
        {p.variants&&<div className="variant-box"><span>Choose dosage</span><div>{p.variants.map(v=><a className={v.slug===slug?"selected":""} href={`/products/${v.slug}`} key={v.slug}>{v.label}<small>${v.price.toFixed(2)}</small></a>)}</div></div>}
        <div className="purchase-row"><div><span>Price per vial</span><strong>${p.price.toFixed(2)}</strong><small>{p.concentration}</small></div><button>Add to Cart</button></div>
      </section>
      <div className="detail-facts"><div><span>⚗</span><p><small>Concentration</small><strong>{p.concentration}</strong></p></div><div><span>▣</span><p><small>Warehouse</small><strong>US Domestic</strong></p></div></div>
      <div className="detail-divider"/>
      <Info title={`🧬 What Is ${p.name}?`} text={p.about!}/><Info title="🔬 Why Researchers Study It" text={p.overview!}/>
      <section><h2 className="detail-heading">🔬 How It Works — Mechanism of Action</h2><div className="mechanism-grid">{p.benefits!.map((b,i)=><div key={b}><span>{["◈","⌁","◎","◇"][i%4]}</span><p><strong>{b}</strong><small>Investigated under controlled laboratory conditions as part of ongoing molecular and pathway research.</small></p></div>)}</div></section>
      <section><h2 className="detail-heading">📚 Current Research Areas</h2><div className="research-grid">{p.benefits!.map(b=><div key={b}>⚗ <span>{b}</span></div>)}</div></section>
      <section><h2 className="detail-heading">❓ Frequently Asked Questions</h2><div className="faq-list">{[`What is the purity of ${p.name}?`,`How should I reconstitute this peptide?`,`What storage conditions are recommended?`,`What research has been conducted on ${p.name}?`,`What are the key research pathways of ${p.name}?`,`Is ${p.name} suitable for my research protocol?`].map(q=><details key={q}><summary>{q}<span>⌄</span></summary><p>Product information is provided for qualified laboratory researchers. Review available analytical documentation and follow your institution's approved research protocols.</p></details>)}</div></section>
      {p.coa&&<section><h2 className="detail-heading">▤ Certificate of Analysis (Janoshik)</h2><div className="coa-status"><strong>Third-Party Lab Verified</strong>{p.coaDate&&<span>Report date: {p.coaDate}</span>}<a href={p.coa} target="_blank" rel="noreferrer">Verify on Janoshik.com ↗</a></div>{p.coaImage&&<div className="coa-image"><img src={`${OLD}${p.coaImage}`} alt={`${p.name} Certificate of Analysis`}/></div>}</section>}
      <section className="beauty-promo"><div className="spark">✦</div><div><h3>Looking for Education or Personalized Guidance?</h3><p><strong>Lion Elite Beauty</strong> offers educational coaching, accountability, and personalized wellness support for individuals looking to better understand their health and transformation journey — separate from our research peptide catalog.</p></div><a href="https://lionelitebeauty.com" target="_blank" rel="noreferrer">Learn More →</a></section>
      <div className="research-notice"><strong>Research Use Only</strong><p>This product is intended solely for laboratory research and analytical purposes. Not for human consumption or veterinary use. Not intended to diagnose, treat, cure, or prevent any disease. Statements have not been evaluated by the FDA.</p></div>
      <div className="detail-bottom"><a href="/">View Full Catalog</a></div>
    </div>
  </main>;
}

function Info({title,text}:{title:string;text:string}) { return <section><h2 className="detail-heading">{title}</h2><div className="detail-info"><p>{text}</p></div></section> }
